apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: nuvolaris
spec:
  secretName: registry-tls-secret
  duration: 2160h
  renewBefore: 360h
  commonName: registry.miniops.me
  dnsNames:
  - registry.miniops.me
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
